stages:
  - build
  - test
  - publish

variables:
  typ:
    value: build
    description: "Pipeline type. Valid options are: 'build', 'test' or 'release'."
  wersja:
    value: 1.0.0
    description: "Version"


build-plugins:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
      when: always
    - if: $CI_MERGE_REQUEST_IID
    - if: $typ == 'build'
    - if: $typ == 'test'
  tags:
    - Windows
  script:
    - 'nuget restore'
    - 'msbuild Updater.sln /p:ReferencePath="$env:MISTAKEN_REFERENCES" /p:CompanyName=Mistaken /p:OutputPath="build"'
  artifacts:
    paths:
      - Updater\build\Mistaken.Updater.dll

test-plugins:
  needs: [build-plugins]
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $typ == 'test'
  stage: test
  tags:
   - Linux
  dependencies:
   - build-plugins
  script:
    - ls -la
    - 'curl -o "CI Tester" -H "PRIVATE-TOKEN: $API_KEY" "https://git.mistaken.pl/api/v4/projects/Barwa%2FCI-Tools/jobs/artifacts/main/raw/build/CI%20Tester?job=build-code-job"'
    - /home/barwa/unzip_gitlab.sh
  
build-plugins-publish:
  stage: build
  rules:
    - if: $typ == 'release'
  tags:
    - Windows
  script:
    - 'nuget restore'
    - 'msbuild Updater.sln /p:ReferencePath="$env:MISTAKEN_REFERENCES" /p:CompanyName=Mistaken /p:OutputPath="build"'
  artifacts:
    paths:
      - Updater\build\Mistaken.Updater.dll

test-plugins-publish:
  needs: [build-plugins-publish]
  rules:
    - if: $typ == 'release'
  stage: test
  tags:
   - Linux
  dependencies:
    - build-plugins-publish
  script:
    - ls -la
    - 'curl -o "CI Tester" -H "PRIVATE-TOKEN: $API_KEY" "https://git.mistaken.pl/api/v4/projects/Barwa%2FCI-Tools/jobs/artifacts/main/raw/build/CI%20Tester?job=build-code-job"'
    - /home/barwa/unzip_gitlab.sh
  
publish-plugins:
  needs: [build-plugins-publish, test-plugins-publish]
  rules:
    - if: $typ == 'release'
  stage: publish
  tags:
    - Windows
  dependencies:
    - build-plugins-publish
  script:
    - 'curl -InFile "Updater\build\Mistaken.Updater.dll" -Method "Put" -H @{"PRIVATE-TOKEN"= "$API_KEY"} "https://git.mistaken.pl/api/v4/projects/scp-sl%2Fupdater/packages/generic/plugins/$wersja/Mistaken.Updater.dll" -UseBasicParsing'
    - $env:asset = "{`"name`":`"Mistaken.Updater.dll`",`"url`":`"https://git.mistaken.pl/api/v4/projects/scp-sl%2Fupdater/packages/generic/plugins/$wersja/Mistaken.Updater.dll`"}"
    - $env:assetjson = $env:asset | ConvertTo-Json
    - C:\GitLab\Release-CLI\bin\release-cli create --name $wersja --description "Release $wersja" --tag-name $wersja --assets-link=$env:assetjson
    - git clone https://oauth2:$GIT_KEY@git.mistaken.pl/scp-sl/dependencies.git
    - cd dependencies
    - cp ..\Updater\build\Mistaken.Updater.dll Mistaken.Updater.dll
    - git config commit.gpgsign false
    - git config user.email "ci@git.mistaken.pl"
    - git config user.name "Gitlab-CI"
    - git add Mistaken.Updater.dll
    - git commit -m "Update Mistaken.Updater"
    - git push
    - cd ..
    - rm -r dependencies
    - git remote set-url origin https://oauth2:$GIT_KEY@git.mistaken.pl/scp-sl/updater.git
    - git config commit.gpgsign false
    - git config user.email "ci@git.mistaken.pl"
    - git config user.name "Gitlab-CI"
    - git checkout master
    - echo $wersja > version
    - git add version
    - git commit -m "[ci skip] bump version"
    - git push origin master
